webtalk_init -webtalk_dir D:/Users/matej/Desktop/Documents/FEKT/DE1/DE1-Projekt-2/DE1-Projekt-2.sim/sim_1/behav/xsim/xsim.dir/tb_lock_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May  3 19:42:15 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a9bab5f4-1423-44f6-8a9d-8a1652addcce" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "347167cb6c16432bb9c47a4047d9cdb8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "52" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3504 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "18 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6624_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3702886944 -regid "" -xml D:/Users/matej/Desktop/Documents/FEKT/DE1/DE1-Projekt-2/DE1-Projekt-2.sim/sim_1/behav/xsim/xsim.dir/tb_lock_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Users/matej/Desktop/Documents/FEKT/DE1/DE1-Projekt-2/DE1-Projekt-2.sim/sim_1/behav/xsim/xsim.dir/tb_lock_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Users/matej/Desktop/Documents/FEKT/DE1/DE1-Projekt-2/DE1-Projekt-2.sim/sim_1/behav/xsim/xsim.dir/tb_lock_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
